image: node:lts

pages:
  stage: deploy
  script:
    - cd nn-demonstrator
    - npm ci
    - npm run build
    - rm -rf ../public # Remove any existing public dir at root to avoid conflicts
    - mv dist ../public # Move dist to root public for GitLab Pages
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH
